### ISSUE TITLE
Download from file explorer does not work

### ISSUE THREAD

**Issue by bpasero** [MicrosoftDocs/vscodespaces#292]
Right-click on a file and select download. You will see a download started but the file is empty:

![image](https://user-images.githubusercontent.com/900690/73250311-eb8d9800-41b6-11ea-8cc1-cc705a8cc0e3.png)

I believe this is an issue with using service workers in-between for this download URL. I am thinking of changing VSCode's download feature to use blob URIs to circumvent this. See https://github.com/microsoft/vscode/issues/89407

**Comment by srivatsn** [comment]
Thanks @bpasero. I verified in a dev deployment that this fix works! We'll push it to prod next week.

**Comment by bpasero** [comment]
@srivatsn sounds good.

**Comment by nikmd23** [comment]
👏🏻 yey!

This has been a paper cut that regularly gets me. Glad we have a fix coming. Thanks guys

**Comment by jkeech** [comment]
@bpasero, will this also fix #282? Or will you still be required to invoke the download command directly?

**Comment by bpasero** [comment]
@jkeech unfortunately it probably will not fix #282 because the fix involved creating a URL in memory which is resolved from a long running operation. I do not think a long running operation can be done during the drag phase.

**Comment by bpasero** [comment]
I am quite sure that this is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=741778

**Comment by bpasero** [comment]
I think the original root cause of this issue was/is: https://bugs.chromium.org/p/chromium/issues/detail?id=468227

**Comment by lostintangent** [comment]
@bpasero Is this now resolved via https://github.com/microsoft/vscode/issues/89407?

**Comment by srivatsn** [comment]
Yes this is how fixed.

**Comment by jkeech** [comment]
Reopening since this error still happens for large file downloads (such as #509)

**Comment by lostintangent** [comment]
Closing as a duplicate of #517.
