### ISSUE TITLE
Codespace can't redirect request to Spring Boot app port 8080

### ISSUE THREAD

**Issue by waltercoan** [MicrosoftDocs/vscodespaces#493]
Hi,

I'm trying to use Visual Studio Code online with my students in they class about how to develop web app using Spring Boot. My app use Thymeleaf plugging to generate the HTML interface. This screen is the app running in VSCode online.
![image](https://user-images.githubusercontent.com/7109985/81741324-c591b800-9474-11ea-9fff-cf7150cf4bce.png)
If I curl http://localhost:8080 in another bash into VSCode I can get the page.
![image](https://user-images.githubusercontent.com/7109985/81741485-0689cc80-9475-11ea-91cf-92b100aeb834.png)
But when I try to open with the redirect from codespace that error happens
![image](https://user-images.githubusercontent.com/7109985/81741593-30db8a00-9475-11ea-850b-ed311aba0a4d.png)
![image](https://user-images.githubusercontent.com/7109985/81741612-376a0180-9475-11ea-97f3-6936b3fc8cc1.png)

**Comment by jkeech** [comment]
@plisy, is this due to the service worker port forwarding implementation?

@waltercoan, one potential workaround is to connect to the Codespace from VS Code on the desktop. In the desktop case, the port forwarding implementation is more complete and it should work exactly as you expect.

**Comment by waltercoan** [comment]
Hi @jkeech, thanks for your quick feedback. I am using visual studio online because we are taking virtual classes during the pandemic quarentine. Not all of my students have computers good enough to run this environment, so Visual Studio online proved to be an excellent solution. I chatted with Mr. Michael Crump (@mbcrump) on twitter, because I had the same problem with ASP.NET core. For the redirection to work I had to disable the HTTPSRedirection of the project and then the redirection worked correctly. But in the case of Spring it must be another problem because it does not use https by default. Anyway, I will try the visual studio desktop option for online. Thank you!

**Comment by plisy** [comment]
@jkeech Yes, our implementation isn't able to parse responses from some servers properly.

**Comment by jkeech** [comment]
@waltercoan, we are working on a new port forwarding service for the browser which will be closer to feature parity with the desktop implementation of port forwarding. I understand that the current experience in the web doesn't work for you ☹️. Unfortunately, the best solution for now is to use VS Code desktop for the set of apps that you can't successfully port-forward in the browser today. 

Alternatively, you could try using a different service/tool for port-forwarding from within the container, such as ngrok. The difference between something like ngrok and the Codespaces port-forwarding is that the Codespaces one is not visible on the public internet and is only visible to the person who owns the Codespace, so it's more private/secure by default. But as a short term solution, something like ngrok might meet your needs if you cannot use VS Code desktop.

**Comment by mdireskeneli** [comment]
I am having the same problem. It is impossible to work with spring-boot & java applications in code spaces and use this port-forwarding. It works fine with node-js servers.

**Comment by waltercoan** [comment]
@mdireskeneli if you install Visual Studio Code desktop and install the Codespaces extension, you can use Spring-boot and Java. You will code into your Visual Studio Desktop but the workload will be do into the codespace in Azure.

**Comment by lostintangent** [comment]
This should now be resolved! Please let us know if you run into any issues. Thanks!

**Comment by anirudhb** [comment]
Still getting this issue with Flutter web, seeing a lot of 500's in the console.

**Comment by mdireskeneli** [comment]
I have tried code-server lately which is an alternative and doesn't have this remote connection problem.

**Comment by wpitallo** [comment]
I get this too cannot run over https :(

**Comment by waltercoan** [comment]
> I get this too cannot forward ports over https :(

Hi @wpitallo, use the VSCode app in your computer and install the Code Space extension, doing that will works fine!

**Comment by plisy** [comment]
@wpitallo https should now work on web, at the moment it won't work on desktop though. In case it doesn't work on web, can you please try clearing site data or a different port.

**Comment by wpitallo** [comment]
@plisy changed the port still getting this: 

![Uploading image.png…]()

**Comment by plisy** [comment]
@wpitallo any chance your app is a repo I could fork and try to get it running?

The one scenario I know about where this might be the result is when the server is not reachable on localhost by our agent in the codespace. I still don't know what the root cause is and need to investigate.
